# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.2-r2.0
project_group=net.rebel459.music_and_melody
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=music_and_melody
mod_name=Music And Melody
mod_description=An advanced music player, fitting soundtrack expansion, powerful playback system and vanilla music fixes as one comprehensive solution
sources_url=https://github.com/Rebel459/music-and-melody
issues_url=https://github.com/Rebel459/music-and-melody/issues

# Minecraft
minecraft_version=26.2
neo_form_version=26.2-1

# Fabric
fabric_loader=0.19.3
fabric_api=0.156.0+26.2
fabric_minecraft_version=>=26.2 <26.3

# NeoForge
neoforge_version=26.2.0.45-beta
neoforge_minecraft_version=[26.2, 26.3)

# Common Dependencies
unified_version=26.2-r2.5
cloth_version=26.2.155

simple_music_control=1.5.0+26.2
fzzy_version=0.7.6+26.2
fancymenu_version=3.9.9-26.2

# Fabric Dependencies
modmenu_version=20.0.1
kotlin_fabric=1.13.13+kotlin.2.4.10
enderscape_fabric=3.0.0
devauth_fabric=1.1.1

# NeoForge Dependencies
kotlin_neoforge=6.3.0