# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r3.1
project_group=net.rebel459.music_and_melody
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=music_and_melody
mod_name=Music And Melody
mod_description=Comprehensive music overhaul powered by Albums, Events and Playlists, alongside a fitting soundtrack expansion and various music tweaks
sources_url=https://github.com/Rebel459/music-and-melody
issues_url=https://github.com/Rebel459/music-and-melody/issues

# Minecraft
minecraft_version=26.1.2
neo_form_version=26.1.2-1

# Fabric
fabric_loader=0.19.2
fabric_api=0.149.1+26.1.2
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.2.63-beta
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r4.1
cloth_version=26.1.154

simple_music_control=1.4.2+26.1
fzzy_version=0.7.6+26.1

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8
kotlin_fabric=1.13.11+kotlin.2.3.21

# NeoForge Dependencies
kotlin_neoforge=6.2.0