# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r3.0
project_group=net.rebel459.music_and_melody
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=music_and_melody
mod_name=Music And Melody
mod_description=Comprehensive music improvements with a configurable album system, fitting soundtrack overhaul and a collection of music fixes & tweaks
sources_url=https://github.com/Rebel459/music-and-melody
issues_url=https://github.com/Rebel459/music-and-melody/issues

# Minecraft
minecraft_version=26.1
neo_form_version=26.1-1

# Fabric
fabric_loader=0.19.2
fabric_api=0.144.3+26.1
fabric_minecraft_version=>=26.1 <26.3

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_minecraft_version=[26.1, 26.3)

# Common Dependencies
unified_version=26.1-r4.1
cloth_version=26.1.154

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8