modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/Rebel459/legacies-and-legends/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}-neoforge"
displayName="${mod_name}"
displayURL="https://github.com/Rebel459/legacies-and-legends"
logoFile="assets/icon.png"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${neoforge_minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="unified"
type="required"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"

[[dependencies.${mod_id}]]
modId="item_tooltips"
type="required"

[[dependencies.${mod_id}]]
modId="trimpatcher"
type="required"

[[dependencies.${mod_id}]]
modId="lithostitched"
type="required"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "legacies_and_legends.mixins.json"
[[mixins]]
config = "legacies_and_legends-neoforge.mixins.json"