modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}-neoforge"
displayName="${mod_name}"
displayURL="${sources_url}"
logoFile="assets/music_and_melody/icon.png"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${neoforge_minecraft_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config = "music_and_melody.mixins.json"
[[mixins]]
config = "music_and_melody-neoforge.mixins.json"